### ISSUE TITLE
fb.py fail 

### ISSUE THREAD

**Issue by gearcapitan** [x0rz/EQGRP_Lost_in_Translation#3]
C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows>fb.py

--[ Version 3.5.1

[*] Loading Plugins
===============================================================
=
= Encountered an unhandled error.  Please provide the following
= information to the developer
=
===============================================================
Traceback (most recent call last):
  File "C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows\fuzzbunch\exception.py", line 66, in wrap
    ret = fn(*args, **kwargs)
  File "C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows\fb.py", line 83, in setup_and_run
    load_plugins(fb)
  File "C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows\fb.py", line 72, in load_plugins
    addplugins(fb, "ListeningPost", LP_DIR,      EDFPlugin)
  File "C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows\fuzzbunch\pluginfinder.py", line 78, in addplugins
    plugins = getpluginlist(location, bin)
  File "C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows\fuzzbunch\pluginfinder.py", line 36, in getpluginlist
    fblist     = getextensionfiles(location, FB_CONFIG_EXT)         # get list of .fb files
  File "C:\Users\gearc\Documents\EQGRP_Lost_in_Translation-master\windows\fuzzbunch\pluginfinder.py", line 21, in getextensionfiles
    for file in os.listdir(location)
WindowsError: [Error 3] El sistema no puede encontrar la ruta especificada: 'C:\\Users\\gearc\\Documents\\EQGRP_Lost_in_Translation-master\\windows\\listeningposts/*.*'

![sin titulo](https://cloud.githubusercontent.com/assets/13740942/25145269/5841c59e-2436-11e7-93a7-0a0d898ebf7c.png)

**Comment by Luuk1979** [comment]
Same here. All installed on windows 7 enterprise x86 
x0rz what platform + architecture you use?

**Comment by gearcapitan** [comment]
win 7 pro x64 and win 10 pro x64

**Comment by Luuk1979** [comment]
Anything special about the installation. I installed neccesary components. pywin32, pyhton-2.6.6.msi and jre-6u15, added python to path. thats is?

**Comment by gearcapitan** [comment]
yes :/

**Comment by gearcapitan** [comment]
![windows xp professional-2017-04-18-13-54-34](https://cloud.githubusercontent.com/assets/13740942/25147880/935be260-243e-11e7-84ed-77247fd2e485.png)

**Comment by chester0** [comment]
from fb.py:
comment out or delete lines: 26, 27, 28, 74, 75.
you need pywin32 on windows too.

**Comment by PaulusParssinen** [comment]
I just added that folder /listeningposts/ and it started working, not sure why hh

**Comment by chester0** [comment]
that folder is missing from the source

**Comment by Luuk1979** [comment]
Gotcha.
